# Generated by Django 5.0.6 on 2024-07-07 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='Asunto', max_length=250)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
