# Generated by Django 5.0.6 on 2024-07-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_servicio', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
