# Generated by Django 5.0.6 on 2024-07-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postservicio',
            old_name='Tipo_servicio',
            new_name='Servicio',
        ),
    ]
