# Generated by Django 5.0.6 on 2024-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_tipo_servicio_postservicio_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicionombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostServicio',
        ),
    ]
