# Generated by Django 5.0.6 on 2024-07-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_delete_postservicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Servicionombre',
            new_name='Nombre',
        ),
    ]
