# Generated by Django 5.0.6 on 2024-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_rename_servicionombre_servicio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Descripcion',
            field=models.TextField(max_length=500000),
        ),
    ]
