# Generated by Django 5.0.6 on 2024-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='telefonocontacto',
            field=models.IntegerField(null=True),
        ),
    ]
